# Proxy configuration for TARS with LiteLLM
# This values file enables the LiteLLM proxy and configures the agent to use it
# Usage: helm install tars . -f values-proxy.yaml

# Enable LiteLLM proxy
tars-llm-proxy:
  enabled: true
  fullnameOverride: "tars-llm-proxy"
  env:
    # Set your API keys here
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"

# Configure agent to use the proxy
tars-agent:
  config:
    llmProxyUrl: "http://tars-llm-proxy:4000"
  # Don't set API keys on the agent when using proxy
  env:
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""

# All other services remain the same
postgresql:
  enabled: true

tars-desktop:
  enabled: true

tars-ui:
  enabled: true

# Optional: Enable ingress for external access
ingress:
  enabled: false
  className: "nginx"
  host: tars.example.com
  tls:
    enabled: true
    secretName: tars-tls